"""Indoone AI core entry point.

The service keeps inference local and provider-independent. Every successful
user-facing answer is generated by the trained Indoone model.
"""

from datetime import datetime, timedelta, timezone
import asyncio
from pathlib import Path
import logging
import os
import threading
from typing import TYPE_CHECKING
import re
import time

from app.storage.github_release import GitHubReleaseStorageError, get_github_release_storage
from app.ai.research import build_research_provider, format_research_context


logger = logging.getLogger(__name__)

def _qwen_backend_enabled() -> bool:
    return os.getenv("INDOONE_MODEL_BACKEND", "").strip().casefold() == "qwen"


def _gemma_backend_enabled() -> bool:
    return os.getenv("INDOONE_MODEL_BACKEND", "").strip().casefold() == "gemma"

if TYPE_CHECKING:
    from app.ai.inference import LocalModelRuntime

# Kept as a lazy injection point for tests and compatibility. The real class is
# imported only inside _load_local_model_runtime() so Render startup stays light.
LocalModelRuntime = None

MODEL_DIR = Path("models/indoone-small")
_checkpoint = MODEL_DIR / "indoone-small.pt"
_tokenizer = MODEL_DIR / "tokenizer.json"
# Keep model loading entirely request-driven. Constructing LocalAIEngine at import
# time can eagerly load the full PyTorch checkpoint during Render startup, which
# increases memory pressure and can cause the web process to restart before chat.
_runtime: "LocalModelRuntime | None" = None
_NEXT_MODEL_LOAD_ATTEMPT = 0.0
_MODEL_LOAD_RETRY_SECONDS = 60.0
_MODEL_MAX_NEW_TOKENS = 512
# Serialize the artifact check/runtime load so concurrent chat requests cannot
# trigger duplicate B2 downloads or duplicate model loads.
_MODEL_LOAD_LOCK = threading.Lock()
_MODEL_INFERENCE_LOCK = threading.Lock()
_ARTIFACT_CHECK_COMPLETED = False


_WEB_RESEARCH_ENABLED = os.getenv(
    "INDOONE_ALWAYS_WEB_RESEARCH", "true"
).strip().casefold() in {"1", "true", "yes", "on"}
_WEB_RESEARCH_MODE = os.getenv("INDOONE_WEB_RESEARCH_MODE", "conditional").strip().casefold()
_WEB_RESEARCH_TIMEOUT_SECONDS = 15.0
_WEB_RESEARCH_MAX_RESULTS = 5
_WEB_RESEARCH_CACHE_TTL_SECONDS = 30.0
_WEB_RESEARCH_MIN_INTERVAL_SECONDS = 1.0
_WEB_RESEARCH_CACHE: dict[str, tuple[float, str]] = {}
_WEB_RESEARCH_LOCK = asyncio.Lock()
_WEB_RESEARCH_LAST_REQUEST_AT = 0.0

_WEB_FRESHNESS_MARKERS = (
    "latest", "current", "currently", "today", "yesterday", "tomorrow", "recent",
    "news", "live", "price", "cost", "stock price", "weather", "score", "scores",
    "result", "results", "availability", "available now", "update", "updates",
    "announcement", "official announcement", "release", "released", "new version",
    "current version", "search the web", "search online", "look it up",
    "on the internet", "internet", "google", "duckduckgo",
    "ಇಂದಿನ", "ಇತ್ತೀಚಿನ", "ಸುದ್ದಿ", "ಬೆಲೆ", "ಹವಾಮಾನ", "ಚುನಾವಣೆ", "ಪ್ರಸ್ತುತ",
)
_WEB_VOLATILE_ROLE_MARKERS = (
    "who is the president", "who is president", "prime minister of", "chief minister of",
    "current minister", "current ceo", "who is the ceo", "government of",
)
_WEB_NO_WEB_MARKERS = (
    "without web", "offline", "don't search", "do not search", "no web",
)

def _should_use_live_web(message: str) -> bool:
    """Route only freshness-sensitive or explicitly web-seeking requests to live search."""
    normalized = " ".join(message.casefold().split())
    if any(marker in normalized for marker in _WEB_NO_WEB_MARKERS):
        return False

    if _WEB_RESEARCH_MODE in {"off", "disabled"}:
        return False
    if _WEB_RESEARCH_MODE in {"always", "force"}:
        return True

    if any(marker in normalized for marker in _WEB_FRESHNESS_MARKERS):
        return True
    if any(marker in normalized for marker in _WEB_VOLATILE_ROLE_MARKERS):
        return True
    if re.search(r"\b20(?:2[6-9]|3\d)\b", normalized):
        return True
    return False


async def _collect_live_web_context(message: str) -> str:
    """Collect live web evidence only when the backend router decides it is needed."""
    global _WEB_RESEARCH_LAST_REQUEST_AT

    if not _WEB_RESEARCH_ENABLED:
        logger.info("web research disabled: local-model answer path")
        return ""
    if not _should_use_live_web(message):
        logger.info("web route skipped: local-model answer path")
        return ""

    cache_key = " ".join(message.casefold().split())
    now = time.monotonic()
    cached = _WEB_RESEARCH_CACHE.get(cache_key)
    if cached and now - cached[0] <= _WEB_RESEARCH_CACHE_TTL_SECONDS:
        logger.info("web cache hit: query=%s", cache_key[:120])
        return cached[1]

    started = time.perf_counter()
    async with _WEB_RESEARCH_LOCK:
        now = time.monotonic()
        cached = _WEB_RESEARCH_CACHE.get(cache_key)
        if cached and now - cached[0] <= _WEB_RESEARCH_CACHE_TTL_SECONDS:
            logger.info("web cache hit after queue: query=%s", cache_key[:120])
            return cached[1]

        delay = _WEB_RESEARCH_MIN_INTERVAL_SECONDS - (
            now - _WEB_RESEARCH_LAST_REQUEST_AT
        )
        if delay > 0:
            await asyncio.sleep(delay)

        _WEB_RESEARCH_LAST_REQUEST_AT = time.monotonic()
        try:
            provider = build_research_provider()
            results = await asyncio.wait_for(
                provider.search(message, limit=_WEB_RESEARCH_MAX_RESULTS),
                timeout=_WEB_RESEARCH_TIMEOUT_SECONDS,
            )
        except Exception as exc:
            logger.warning("live web research failed; continuing without web context: %s", exc)
            return ""

        duration_ms = round((time.perf_counter() - started) * 1000, 2)
        logger.info(
            "live web research completed: results=%s duration_ms=%s",
            len(results),
            duration_ms,
        )

        context = format_research_context(
            results,
            max_results=_WEB_RESEARCH_MAX_RESULTS,
            max_title_chars=70,
            max_snippet_chars=140,
        )
        _WEB_RESEARCH_CACHE[cache_key] = (time.monotonic(), context)
        return context


def _ensure_model_artifacts(model_dir: Path) -> None:
    """Load model artifacts only from the configured private Indoone-Model release."""
    github_storage = get_github_release_storage()
    if github_storage is None:
        raise GitHubReleaseStorageError(
            "Indoone model serving requires GITHUB_MODEL_REPOSITORY, "
            "GITHUB_MODEL_RELEASE_TAG, and GITHUB_MODEL_TOKEN"
        )

    artifacts = {
        "indoone-small.pt": model_dir / "indoone-small.pt",
        "tokenizer.json": model_dir / "tokenizer.json",
    }
    for filename, local_path in artifacts.items():
        if local_path.exists():
            continue
        github_storage.download_file(filename, local_path)


def _next_utc_midnight_timestamp() -> float:
    """Back off failed remote model-artifact downloads until the next UTC day."""
    now = datetime.now(timezone.utc)
    tomorrow = (now + timedelta(days=1)).date()
    midnight = datetime.combine(tomorrow, datetime.min.time(), tzinfo=timezone.utc)
    return midnight.timestamp()


def _load_local_model_runtime() -> "LocalModelRuntime | None":
    """Load the trained checkpoint with a single-flight artifact download/load."""
    global _runtime, _NEXT_MODEL_LOAD_ATTEMPT, _ARTIFACT_CHECK_COMPLETED

    if _runtime is not None:
        return _runtime

    if not _MODEL_LOAD_LOCK.acquire(blocking=False):
        logger.info("Indoone model load already in progress; another request will reuse the loaded runtime")
        return None

    try:
        # A concurrent request may have completed the model load while this
        # request was waiting for the lock.
        if _runtime is not None:
            return _runtime

        now = time.time()
        if now < _NEXT_MODEL_LOAD_ATTEMPT:
            return None

        if not _ARTIFACT_CHECK_COMPLETED:
            try:
                _ensure_model_artifacts(MODEL_DIR)
                if get_github_release_storage() is not None:
                    logger.info("Indoone model artifacts checked from private GitHub Release")
                else:
                    logger.info("Indoone model artifact check completed from private Indoone-Model GitHub Release")
            except GitHubReleaseStorageError as exc:
                _NEXT_MODEL_LOAD_ATTEMPT = _next_utc_midnight_timestamp()
                logger.error("Indoone model artifact check failed: %s", exc)
                return None

            if not (_checkpoint.exists() and _tokenizer.exists()):
                _NEXT_MODEL_LOAD_ATTEMPT = _next_utc_midnight_timestamp()
                logger.error(
                    "Indoone local model artifacts are missing: checkpoint=%s tokenizer=%s",
                    _checkpoint.exists(), _tokenizer.exists(),
                )
                return None

            # From this point on, every request in this process uses the local
            # artifacts and never re-checks/downloads them from remote storage.
            _ARTIFACT_CHECK_COMPLETED = True

        try:
            # Import PyTorch/model code only when a chat request actually needs
            # trained-model inference. This keeps Render startup memory low while
            # retaining a testable lazy injection point.
            runtime_factory = LocalModelRuntime
            if runtime_factory is None:
                from app.ai.inference import LocalModelRuntime as runtime_factory

            _runtime = runtime_factory(_checkpoint, _tokenizer)
            _NEXT_MODEL_LOAD_ATTEMPT = 0.0
            logger.info("Indoone local model runtime loaded successfully")
        except Exception as exc:
            _NEXT_MODEL_LOAD_ATTEMPT = now + _MODEL_LOAD_RETRY_SECONDS
            logger.error("Indoone local model runtime failed to load: %s", exc)
            _runtime = None
        return _runtime
    finally:
        _MODEL_LOAD_LOCK.release()


_SCRIPT_RANGES: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("Kannada", re.compile(r"[\u0C80-\u0CFF]")),
    ("Telugu", re.compile(r"[\u0C00-\u0C7F]")),
    ("Tamil", re.compile(r"[\u0B80-\u0BFF]")),
    ("Malayalam", re.compile(r"[\u0D00-\u0D7F]")),
    ("Hindi", re.compile(r"[\u0900-\u097F]")),
    ("Bengali", re.compile(r"[\u0980-\u09FF]")),
    ("Gujarati", re.compile(r"[\u0A80-\u0AFF]")),
    ("Punjabi", re.compile(r"[\u0A00-\u0A7F]")),
    ("Odia", re.compile(r"[\u0B00-\u0B7F]")),
    ("Urdu", re.compile(r"[\u0600-\u06FF]")),
)

_LANGUAGE_NAMES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Kannada", ("kannada", "ಕನ್ನಡ", "ಕನ್ನಡದ")),
    ("Hindi", ("hindi", "हिंदी", "हिन्दी")),
    ("Telugu", ("telugu", "తెలుగు")),
    ("Tamil", ("tamil", "தமிழ்", "தமிழ")),
    ("Malayalam", ("malayalam", "മലയാളം")),
    ("Marathi", ("marathi", "मराठी")),
    ("Bengali", ("bengali", "bangla", "বাংলা", "বাঙালি")),
    ("Assamese", ("assamese", "অসমীয়া", "অসমিয়া")),
    ("Gujarati", ("gujarati", "ગુજરાતી")),
    ("Punjabi", ("punjabi", "ਪੰਜਾਬੀ")),
    ("Odia", ("odia", "oriya", "ଓଡ଼ିଆ", "ଓଡିଆ")),
    ("Urdu", ("urdu", "اردو")),
)

_ROMANIZED_HINTS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Kannada", ("bagge", "helu", "heLi", "maadu", "maadi", "madbeku", "madbekagutte", "enidu", "enu", "yenu", "yenide", "ivaga", "matte", "nanage", "nimage", "nanna", "namma", "ide", "illa", "agide", "beku")),
    ("Hindi", ("kya", "hai", "hain", "mujhe", "aap", "aapko", "batao", "bataiye", "kaise", "kaisa", "kahan", "kyun", "nahi", "abhi", "mera", "meri")),
    ("Telugu", ("enti", "ela", "cheppu", "cheppandi", "undi", "ledu", "nenu", "meeru", "naaku", "emiti", "enduku", "ippudu", "malli")),
    ("Tamil", ("enna", "epdi", "eppadi", "sollu", "sollunga", "irukku", "illa", "naan", "neenga", "enakku", "ippo", "yen")),
    ("Malayalam", ("entha", "engane", "parayu", "parayoo", "undu", "illa", "njan", "ningal", "enikku", "ippo")),
    ("Marathi", ("kay", "aahe", "mala", "tumhi", "sanga", "kasa", "kashi", "kuthe", "ka", "nahi", "aata")),
    ("Bengali", ("ki", "ache", "ami", "apni", "bolo", "bolun", "amar", "keno", "nei")),
    ("Assamese", ("ki", "ase", "moi", "tumi", "kobo", "mur", "kio", "nai")),
    ("Gujarati", ("shu", "che", "chhe", "mane", "tame", "kaho", "kem", "nathi", "maru")),
    ("Punjabi", ("menu", "mainu", "tusi", "daso", "kive", "kiwe", "nahi", "mera", "sanu")),
    ("Odia", ("kana", "achhi", "mu", "tame", "kahantu", "kemiti", "nahi", "ebe")),
    ("Urdu", ("kya", "hai", "mujhe", "aap", "batao", "bataiye", "kaise", "kyun", "nahi")),
)


def _detect_response_language(message: str) -> str:
    normalized = " ".join(message.casefold().split())
    for language, names in _LANGUAGE_NAMES:
        for name in names:
            candidate = name.casefold()
            if re.search(rf"(?<!\w){re.escape(candidate)}(?!\w)", normalized):
                return language
    for language, pattern in _SCRIPT_RANGES:
        if pattern.search(message):
            return language
    scores: dict[str, int] = {}
    for language, hints in _ROMANIZED_HINTS:
        score = sum(
            1
            for hint in hints
            if re.search(rf"(?<!\w){re.escape(hint.casefold())}(?!\w)", normalized)
        )
        if score:
            scores[language] = score
    if scores:
        best_language, best_score = max(scores.items(), key=lambda item: item[1])
        tied = [language for language, score in scores.items() if score == best_score]
        if best_score >= 2 or len(tied) == 1:
            return best_language
    return "English"


def _generate_with_local_model(
    runtime: "LocalModelRuntime",
    context: str,
    language: str,
    temperature: float,
    max_new_tokens: int,
) -> str:
    # Render Free provides a very small CPU budget. Serialize local inference so
    # concurrent requests cannot multiply the model's CPU/memory pressure.
    with _MODEL_INFERENCE_LOCK:
        return runtime.generate(
            context,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            language=language,
        )


class _LocalModelAnswerProvider:
    """Generate every user-facing answer with the trained Indoone model."""

    async def generate(
        self,
        *,
        system_instruction: str,
        user_prompt: str,
        temperature: float = 0.2,
        max_output_tokens: int = _MODEL_MAX_NEW_TOKENS,
    ) -> str:
        runtime = _load_local_model_runtime()
        if runtime is None:
            raise RuntimeError("trained Indoone local model is unavailable")

        context = f"{system_instruction.strip()}\n\n{user_prompt.strip()}".strip()
        try:
            return await asyncio.to_thread(
                _generate_with_local_model,
                runtime,
                context,
                _detect_response_language(user_prompt),
                min(temperature, 0.7),
                min(max_output_tokens, _MODEL_MAX_NEW_TOKENS),
            )
        except (RuntimeError, ValueError) as exc:
            raise RuntimeError("trained Indoone local model generation failed") from exc


_model_answer_provider = _LocalModelAnswerProvider()


class LocalAIService:
    """Direct local-model answer entry point."""

    async def generate(
        self,
        message: str,
        history: list[tuple[str, str]] | None = None,
        document_context: str = "",
    ) -> str:
        cleaned_message = message.strip()
        if not cleaned_message:
            raise ValueError("message cannot be empty")
        live_web_context = await _collect_live_web_context(cleaned_message)
        if live_web_context:
            if document_context:
                document_context = (
                    "LIVE WEB RESEARCH EVIDENCE:\n"
                    + live_web_context
                    + "\n\n"
                    + document_context
                )
            else:
                document_context = "LIVE WEB RESEARCH EVIDENCE:\n" + live_web_context

        prompt_parts = [cleaned_message]

        if history:
            history_lines = []
            for role, content in history[-12:]:
                clean_content = " ".join(str(content).split()).strip()
                if clean_content:
                    history_lines.append(f"{role}: {clean_content[:4_000]}")
            if history_lines:
                prompt_parts.extend(["", "CONVERSATION HISTORY:", *history_lines])

        if document_context.strip():
            prompt_parts.extend(["", "USER-PROVIDED DOCUMENT:", document_context.strip()[:100_000]])

        if _gemma_backend_enabled():
            from app.ai.gemma_service import generate_gemma_reply
            return await generate_gemma_reply(
                cleaned_message,
                history=history,
                document_context=document_context,
            )

        if _qwen_backend_enabled():
            from app.ai.qwen_service import generate_qwen_reply
            return await generate_qwen_reply(
                cleaned_message,
                history=history,
                document_context=document_context,
            )

        if _model_answer_provider is None:
            raise RuntimeError("trained Indoone model provider is unavailable")
        # Keep inference on the same prompt distribution used during SFT:
        # <instruction> contains the user's request directly, without injecting
        # a long runtime policy/system prefix that was not part of training.
        return await _model_answer_provider.generate(
            system_instruction="",
            user_prompt="\n".join(prompt_parts),
            temperature=0.0,
            max_output_tokens=_MODEL_MAX_NEW_TOKENS,
        )

async def generate_reply(
    message: str,
    history: list[tuple[str, str]] | None = None,
    document_context: str = "",
) -> str:
    return await LocalAIService().generate(
        message,
        history=history,
        document_context=document_context,
    )
