"""Indoone AI core entry point.

The service keeps inference local and provider-independent. Every successful
user-facing answer is generated by the trained Indoone model.
"""

from datetime import datetime, timedelta, timezone
import asyncio
from pathlib import Path
import logging
import threading
from typing import TYPE_CHECKING
import re
import time
from app.ai.knowledge import LocalKnowledgeBase, format_hits
from app.ai.research import ResearchProvider, build_research_provider
from app.storage.b2 import B2StorageError, ensure_model_artifacts
from app.storage.github_release import GitHubReleaseStorageError, get_github_release_storage


logger = logging.getLogger(__name__)

if TYPE_CHECKING:
    from app.ai.inference import LocalModelRuntime

# Kept as a lazy injection point for tests and compatibility. The real class is
# imported only inside _load_local_model_runtime() so Render startup stays light.
LocalModelRuntime = None

class _LocalModelAnswerProvider:
    """Adapter that uses the trained Indoone Transformer as the universal generator."""

    async def generate(
        self,
        *,
        system_instruction: str,
        user_prompt: str,
        temperature: float = 0.2,
        max_output_tokens: int = 192,
    ) -> str:
        runtime = _load_local_model_runtime()
        if runtime is None:
            raise RuntimeError("trained Indoone local model is unavailable")
        context = f"{system_instruction.strip()}\n\n{user_prompt.strip()}".strip()
        return await asyncio.to_thread(
            _generate_with_local_model,
            runtime,
            context,
            _detect_response_language(user_prompt),
            min(temperature, 0.7),
            min(max_output_tokens, 192),
        )


from app.ai.universal_qa import UniversalQuestionAnswerPipeline


_universal_answer_provider = _LocalModelAnswerProvider()


class LocalAIService:
    """Compatibility entry point backed by the universal QA pipeline."""

    async def generate(
        self,
        message: str,
        history: list[tuple[str, str]] | None = None,
        document_context: str = "",
    ) -> str:
        pipeline = UniversalQuestionAnswerPipeline(
            _universal_answer_provider,
            research_provider=_research_provider,
            knowledge_base=_knowledge_base,
        )
        reply = await pipeline.answer(
            message,
            history=history,
            document_context=document_context,
        )

        return reply


async def generate_reply(
    message: str,
    history: list[tuple[str, str]] | None = None,
    document_context: str = "",
) -> str:
    return await LocalAIService().generate(
        message,
        history=history,
        document_context=document_context,
    )
